application: party-music
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /main.js
  static_files: static/main.js
  upload: static/main.js
